# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
  DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
  PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
  TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
  TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
  APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
  APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
  APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
  GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]
  CER_GIT_URL = ENV["CER_GIT_URL"]
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)
    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      duration: 1200,
      in_house: false,
      is_key_content_base64: true
    )
    increment_build_number(xcodeproj: "./Runner.xcodeproj")
    match(
      git_url: "#{CER_GIT_URL}",
      type: "appstore",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: GIT_AUTHORIZATION,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key,
      readonly: is_ci
    )
    xcode_select("./Applications/Xcode.app")
    xcodes(version: "15.0.1", select_for_current_build_only: true)
    gym(
      configuration: "Release",
      workspace: "./Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
        },
        signingStyle: "manual"
      },
      clean: true,
      output_name: "app.ipa",       # specify the name of the .ipa file to generate (including file extension)
      codesigning_identity: "Apple Distribution: MIDAS INC",
    )
    upload_to_testflight
    delete_temp_keychain(keychain_name)
  end
end
