# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
  DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
  PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
  TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
  TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
  APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
  APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
  APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
  GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]
  CER_GIT_URL = ENV["CER_GIT_URL"]
  DEVELOPER_PORTAL_TEAM_ID = ENV["DEVELOPER_PORTAL_TEAM_ID"]
  CODE_SIGN_IDENTITY = ENV["CODE_SIGN_IDENTITY"]
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      duration: 1200,
      in_house: false,
      is_key_content_base64: true
    )
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    clean_build_artifacts
    match(
      git_url: "#{CER_GIT_URL}",
      type: "appstore",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: GIT_AUTHORIZATION,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key,
      readonly: is_ci
    )
    xcode_select("/Applications/Xcode.app")
    xcodes(version: "15.0.1", select_for_current_build_only: true)
    gym(
      configuration: "Release",
      codesigning_identity: "Apple Distribution",
      project: "Runner.xcodeproj",
      scheme: "Runner",
      skip_codesigning: true,
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=#{DEVELOPER_PORTAL_TEAM_ID} PROVISIONING_PROFILE_SPECIFIER=#{PROVISIONING_PROFILE_SPECIFIER} CODE_SIGN_IDENTITY=#{CODE_SIGN_IDENTITY}"
    )
    upload_to_testflight(
        api_key: api_key,
    	uses_non_exempt_encryption: false,
    	skip_waiting_for_build_processing: true
    )
    delete_temp_keychain(keychain_name)
  end
end
