# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Workflow

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.0.1
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: init flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Deploy iOS Beta to TestFlight via Fastlane
        env:
          APP_STORE_CONNECT_TEAM_ID: ${{ secrets.DEVELOPER_APP_ID }}
          DEVELOPER_APP_ID: ${{ secrets.DEVELOPER_APP_ID }}
          DEVELOPER_APP_IDENTIFIER: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}
          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
          CER_GIT_URL: ${{ secrets.CER_GIT_URL }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
        run: |
            echo "APP_STORE_CONNECT_TEAM_ID=#{APP_STORE_CONNECT_TEAM_ID}" >> GITHUB_OUTPUT
            echo "DEVELOPER_APP_ID=#{DEVELOPER_APP_ID}" >> GITHUB_OUTPUT
            echo "DEVELOPER_APP_IDENTIFIER=#{DEVELOPER_APP_IDENTIFIER}" >> GITHUB_OUTPUT
            echo "DEVELOPER_PORTAL_TEAM_ID=#{DEVELOPER_PORTAL_TEAM_ID}" >> GITHUB_OUTPUT
            echo "FASTLANE_APPLE_ID=#{FASTLANE_APPLE_ID}" >> GITHUB_OUTPUT
            echo "FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=#{FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD}" >> GITHUB_OUTPUT
            echo "MATCH_PASSWORD=#{MATCH_PASSWORD}" >> GITHUB_OUTPUT
            echo "GIT_AUTHORIZATION=#{GIT_AUTHORIZATION}" >> GITHUB_OUTPUT
            echo "PROVISIONING_PROFILE_SPECIFIER=#{PROVISIONING_PROFILE_SPECIFIER}" >> GITHUB_OUTPUT
            echo "APPLE_KEY_ID=#{APPLE_KEY_ID}" >> GITHUB_OUTPUT
            echo "APPLE_KEY_CONTENT=#{APPLE_KEY_CONTENT}" >> GITHUB_OUTPUT
            echo "CER_GIT_URL=#{CER_GIT_URL}" >> GITHUB_OUTPUT
            echo "TEMP_KEYCHAIN_USER=#{TEMP_KEYCHAIN_USER}" >> GITHUB_OUTPUT
            echo "TEMP_KEYCHAIN_PASSWORD=#{TEMP_KEYCHAIN_PASSWORD}" >> GITHUB_OUTPUT
            cd ios && fastlane beta